### ISSUE TITLE
504 Gateway timeouts

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#858] opened 2021-12-03 15:09 UTC
I've seen this in at least two parts of the site:

1) Exporting users (as in #842)
2) Translation of Pages into new language (eg [translating 514 Pages on Global from English to Karakalpak](https://global.iogt.site/admin/localize/submit/page/10/?next=%2Fadmin%2Fpages%2F10%2F))

This affects the Admin Panel user who is doing the function, and simultaneously all non-admin users of the site will timeout as well.

It doesn't make sense to me to address this only through optimization, eg #844, as we will always scale larger and this issue affects multiple functions.

What is the best practice way to handle these large tasks that take significant time to complete? In RapidPro for example the data export function works in the background and sends an email with a download link when it is complete.

**Comment by geoo89** [comment] 2021-12-06 11:57
It should be possible to mitigate this (at least partially) by increasing the number of instances and/or the number of processes per instance in our deployments, so that the user and other users can still navigate the site while it is busy with some task(s). 

For those operations serving an output to the user, if they are at risk of timing out, I agree we should find a better solution though, such as e-mailing the results or caching the results upon request and putting a download link once the results are ready.

**Comment by cbunicef** [comment] 2021-12-06 14:39
Just to be clear, my understanding is that the translation process does not complete in the background, which is the key concern.

**Comment by geoo89** [comment] 2021-12-06 16:00
I just confirmed that when creating a new locale that is synced from English on global.iogt.site, we get a Gateway Timeout and the operation is not completed.

Interestingly, the process works fine on iogt-global-showcase, possibly due to there being no time out (I don't know if it's faster there, it seems to take 10-15 seconds there).

A current workaround should be going to the English section, and translate individual items or groups of items (i.e. sections with all their children) in smaller batches. (This also has the advantage that a subset of pages can be translated without everything else appearing in English.) However currently on global this doesn't fully work, see #868 .

**Comment by cbunicef** [comment] 2021-12-06 19:00
Even as few as 100 Pages time out during translation, so unfortunately this means at least 36 separate translations to do all the Global content. However realistically users can go Page by Page without too much trouble.

**Comment by cbunicef** [comment] 2021-12-16 17:46
Also affects loading 
https://rw.iogt.site/en/sections/parenting-hub/covid-19-parenting-tips/
https://rw.iogt.site/rw/sections/kinyarwanda-translation-of-parents-caregivers/kinyarwanda-translation-of-covid-19-parenting/

**Comment by cbunicef** [comment] 2021-12-16 19:04
> https://global.iogt.site/es/sections/informacion-de-emergencia/spanish-translation-of-covid-19-parenting/spanish-translation-of-read-to-your-child-about-covid-19/ (Admin: https://global.iogt.site/admin/pages/711/edit/

I was able to solve this by removing the first image content block. The image selected was https://global.iogt.site/admin/images/490/, that page also gives a 504 error when accessing along with https://global.iogt.site/admin/images/491/ which likely causes the 504 error in the same page Arabic version. Both of these images do appear in the Image tab.

**Comment by geoo89** [comment] 2021-12-23 20:21
Large images seem to cause gateway timeouts, see https://github.com/unicef/iogt/issues/926#issuecomment-1000496194

**Comment by geoo89** [comment] 2022-01-13 13:27
The gateway timeouts for large images can be resolved by giving more RAM resources to the server.
This leaves the bulk translation for pages into a new locale, which at least has a workaround.

**Comment by cbunicef** [comment] 2022-01-13 13:53
For posterity, per the discussion last week: the additional resources will allow the server to perform the initial caching of the image assets the first time they are loaded in a given size. There should not be a constant use of large amounts of RAM, but rather once the site is in use it will happen rarely.

**Closed** 2024-04-03 11:36 UTC
Labels: Urgent, Needs internal discussion
