### ISSUE TITLE
Fields in Translation function

### ISSUE THREAD

**Issue by cbunicef** [unicef/iogt#990] opened 2022-01-12 16:32 UTC
Fields which are unnecessary to change at least in the short term can be hidden:

- Relative path to project root dir (seems fixed)
- Application dir (seems fixed)
- Domain (seems fixed)

Should we make "language" and "original" shown but non-editable?

**Comment by geoo89** [comment] 2022-01-17 10:23
Duplicate of #794

**Closed by geoo89** 2022-01-17 10:23 UTC
